### ISSUE TITLE
Build ehighways resolution units

### ISSUE THREAD

**Issue by brynpickering** [calliope-project/euro-calliope#318] opened 2024-04-08 14:47 UTC
### What can be improved?

Take regional level NUTS3 data using the correct NUTS year and aggregate up to eHighways resolution. See "data/statistical_units_to_ehighways_regions.csv" in sector-coupled repo for aggregation mapping

### Version

1.2.0.dev

**Comment by jnnr** [comment] 2024-04-09 08:16
How are ehighways units prepared in Sector-coupled EC currently? They are prepared by the [rule custom_units](https://github.com/brynpickering/euro-calliope/blob/9f59e6fe27172a08745574ec47b498b472bc792f/rules/shapes.smk#L104), which calls the script [aggregate_statistical_units_to_custom_regions.py](https://github.com/brynpickering/euro-calliope/blob/9f59e6fe27172a08745574ec47b498b472bc792f/scripts/shapes/aggregate_statistical_units_to_custom_regions.py)

**Comment by timtroendle** [comment] 2024-04-09 08:38
This seems to be a duplicate of #319, do you agree? Building the shapes seems to be 90% of #319 and because #319 is a feature while this here is not, I'd close this in favour of #318.

**Comment by jonathan-peel** [comment] 2024-04-09 08:49
Terminology:
NUTS3 spatial units (in polygon data types) -> eHighways spatial units (polygons)

**Comment by jonathan-peel** [comment] 2024-04-09 15:51
Desired output: units.geojson file with `MultiPolygon`s all the spatial units for the chosen spatial resolution (regional, national, continental, ehighways, etc.)

**Comment by timtroendle** [comment] 2024-04-10 09:00
I am continuing my nagging here: in the sake of working feature-driven, I would aim for this issue (or #319) to build in eHighways as a feature, not as some data that possibly may be used as a model feature in the future.

Building the shapes sounds like 90% of the way anyway.

**Comment by jnnr** [comment] 2024-04-11 12:37
I agree, @timtroendle. Closing this in favor of #319

**Closed by jnnr** 2024-04-11 12:37 UTC
Labels: enhancement, data
